#include <onion/plugin.h>

#include "plugin_config.h"

ONION_PLUGIN_DEFINE(
    PLUGIN_ID, PLUGIN_VERSION, PLUGIN_NAME,
    ONION_PLUGIN_CAP_IPC | ONION_PLUGIN_CAP_UI,
    ONION_PLUGIN_FLAG_AUTO_START | ONION_PLUGIN_FLAG_LONG_RUNNING |
        ONION_PLUGIN_FLAG_STOP_SUPPORTED);
